services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /srv/docker-data/sonarr/config:/config
      - /srv/docker-data:/data
    ports:
      - 8989:8989
    restart: unless-stopped
