services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
    volumes:
      - /srv/docker-data/plex/config:/config
      - /srv/docker-data/media/tv:/tv
      - /srv/docker-data/media/movies:/movies
    restart: unless-stopped
