services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /srv/docker-data/bazarr/config:/config
      - /srv/docker-data:/data/
    ports:
      - 6767:6767
    restart: unless-stopped
